### ISSUE TITLE
Site feedback — fundamental philosophy

### ISSUE THREAD

**Issue by StevenBlack** [HackFox/hackfox.github.io#2]
This issue pertains to [the site](https://hackfox.github.io/) as seen on January 9, 2020.

A fundamental question appears to be, should the site **reflect the book as printed**?  Or should the site be a **useful reference**?.

If the site is meant to **reflect the book as printed**, then declare victory, and stop.

If the site is meant to **useful reference**, then the following things probably hold:
* Books and websites are fundamentally different media.
* The information architecture of books and websites are different.
* Navigation of books and websites are different.
* The [reading of books and websites are different](https://www.nngroup.com/articles/how-users-read-on-the-web/).

If the site is meant to **useful reference**, then much of the clutter that comes with the book should be eliminated.  Including but not limited to,
* removing blah-blah text in all its manifestations,
* explicit focus on navigation, and text scannability.

To implement this, I propose a ruthless textectomy until nothing but useful technical content remains.  And remove all notion of "sections" and, instead, focus on the navigation of commands, methods, properties, and gotchas.

**Comment by DougHennig** [comment]
I agree with you. My goal was to get the book as printed up so folks could start thinking about what they want, and then make it happen. So, I'm done for now but encourage others to make this the most useful resource it can be.

**Comment by TamarEGranor** [comment]
What do you mean by "blah-blah text," Steve? What kinds of things do you think should be removed?

**Comment by StevenBlack** [comment]
@TamarEGranor I mean, this:  https://www.nngroup.com/articles/blah-blah-text-keep-cut-or-kill/

There are thousands of such instances in the print version of the Hackers Guide.

**Comment by tedroche** [comment]
It sounds like you'd like to write "The Ultimate FoxPro Reference," to reuse a defunct trademark, and I wish you well. Fork the source and have at it! That is why I wished to license the book with an Open Source license, so people could make it useful to them, on their terms. "Scratch your own itch" is an ancient open source trope.

I use an old static HTML version as a reference guide when I need to look something up, and can just skip over the "blah blah blah" (I've read it before) and get the info I need. Or read the narrative that explains I really want to use a different function. Or read about the bugs. Or amuse myself with our self-indulgent, "irrelevant and pretentious quotations" according to one Amazon reviewer.

But, then, I'm an old dinosaur who works in an office with 400 paper books.

To quote [S0C7](https://hackfox.github.io/section0/s0c7.html), "This book is not a replacement for the online Help or the Language Reference manual. It’s a supplement. If something works the way it’s documented, we won’t repeat all the gory details. Instead, we summarize that and add anything the manual doesn’t tell you." So, HF7 was intended as a commentary on the Reference Guide, and a source you go to when you're sure the online Help is misleading. There are key values and pieces ("gory details") missing, and we referred the reader back to the original docs. As you say, that's awkward and frustrating in an online doc. I wished I could have published "The Annotated Reference Guide" that mixed the MS original with HackFox, but there were licensing issues at the time. 

So, if you want to make this a living document, I look forward to seeing what you create.
